# --- MQTT ---
listener 1883
protocol mqtt

# --- Web Socket ---
listener 8883
protocol websockets


# --- TLS ---
# cafile /mosquitto/letsencrypt/fullchain.pem
# certfile /mosquitto/letsencrypt/fullchain.pem
# keyfile /mosquitto/letsencrypt/privkey.pem

# แนะนำให้ใช้ TLS 1.2 ขึ้นไป
tls_version tlsv1.2

# --- Persistence ---
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/

# --- Authentication ---
 allow_anonymous true
# allow_anonymous false
# password_file /mosquitto/config/pwfile
